### ISSUE TITLE
How to Suppress This Error on Arch Linux (name mismatch/version mismatch)

### ISSUE THREAD

**Issue by akano12** [digimezzo/dopamine#356] opened 2022-11-24 13:26 UTC
This is really getting annoying, each time i run a pacman command (any command) i get these 2 errors

`error: local database is inconsistent: name mismatch on package Dopamine-3.0.0`
`error: local database is inconsistent: version mismatch on package Dopamine-3.0.0`

currently have Dopamine-3.0.0 preview.18-1 installed
is there a way to suppress/mute/fix?

**Comment by digimezzo** [comment] 2022-11-24 15:00
Oh! I'm not the only one having this error :) I'll look into it.

**Comment by clankfish** [comment] 2022-11-24 18:14
Also getting this error!

**Comment by digimezzo** [comment] 2022-11-24 19:34
I've looked it up and tried some things. It seems caused by the versioning I'm using to indicate previews, ike: 3.0.0-preview.18. Arch based systems don't like this. Unfortunately you won't be able to get rid of this error. It's something I have to fix. I'll fix it in the next preview. It should be ready in a week or so (I'm adding Last.fm support, and it's progressing rather well).

**Comment by digimezzo** [comment] 2022-11-25 11:11
Fixed in ab469a5ba96473d8caecce5bf50961d226577d12

**Closed by digimezzo** 2022-11-25 11:11 UTC

**Comment by SL-Pirate** [comment] 2022-12-18 16:18
Well I was getting the same error and inspired me to find a fix and found out only fix is to install the thing from the AUR. So I started making a AUR repo and I found @digimezzo was tring it too and found his files. There were some problems with his file but I fixed it and produced a pull request. And also I deployed it to aur under the name `dopamine-appimage`. now waiting for @digimezzo to review my pull request 😉

**Comment by clankfish** [comment] 2022-12-19 13:22
> Well I was getting the same error and inspired me to find a fix and found out only fix is to install the thing from the AUR. So I started making a AUR repo and I found @digimezzo was tring it too and found his files. There were some problems with his file but I fixed it and produced a pull request. And also I deployed it to aur under the name `dopamine-appimage`. now waiting for @digimezzo to review my pull request wink

good shit 👍

**Comment by SL-Pirate** [comment] 2022-12-19 14:19
> good shit +1
u tried it and it works?

**Comment by clankfish** [comment] 2022-12-19 19:12
yep, all good and working on my end. thank you!

**Comment by digimezzo** [comment] 2022-12-20 06:09
@SL-Pirate Thank you for the fix! I planned to add to AUR once it got out of preview, but development is taking too long. It's nice to have the previews in the AUR too :)
I also have a fix in the in the works for the manual .pacman installation.
