### ISSUE TITLE
在文件夹里添加评分后，再切换刷新一下，添加的评分会消失掉

### ISSUE THREAD

**Issue by mouxbo** [digimezzo/dopamine#665] opened 2024-08-28 10:40 UTC

**Comment by digimezzo** [comment] 2024-08-28 16:56
@mouxbo Thanks for logging this bug. I'm adding the translation to English for later reference for me:

`After adding ratings to the folder, switch to refresh and the added ratings will disappear.`

**Comment by digimezzo** [comment] 2024-09-03 03:42
Duplicate of #622

**Closed by digimezzo** 2024-09-03 03:42 UTC
Labels: investigate
