### ISSUE TITLE
Tray Icon Missing In Arch Linux and Windows (to be tested on macOS)

### ISSUE THREAD

**Issue by akano12** [digimezzo/dopamine#696] opened 2024-09-30 10:02 UTC
To reproduce:

1. Open dopamine
2. Check the system tray icon

Expected Behavior:
Dopamine icon should be visible in system tray

Actual Behavior:
A phantom/ghost space appears in the system tray

Screenshots for reference:

![1](https://github.com/user-attachments/assets/364458e5-5a97-4bdd-aca0-dc3308edff7a)
![2](https://github.com/user-attachments/assets/689a3d52-4092-4cdc-a52e-47e3a713751b)

P.S. facing issue on work laptop (Lenovo) and personal laptop (MSI)

**Comment by 413Michele** [comment] 2024-09-30 11:24
I'm having the same problem, this appeared with the latest build (preview.34). I can reproduce this on two PCs:

- Windows 11 x64 with the latest updates, the tray icon is invisible but occupies a space
- Kde Neon with Plasma 6.1, sometimes the tray icon is invisible (same as above), sometimes it is not there at all

Also, clicking on the invisible icon does nothing (no context menu appears)

**Comment by digimezzo** [comment] 2024-09-30 11:31
@413Michele Thanks for the extra info. I indeed have the same problem and seemed to have missed that. I'll have a look at it.

**Comment by akano12** [comment] 2024-09-30 12:19
> @akano12 Which DE is that?

Note sure how i forgot this, it's plasma 6.1.5

And here's another problem caused by this issues, if you have "minimize to tray set on" and close dopamine to tray, you can't open it back as it seems the only way to open dopamine is by clicking on tray icon and click on show dopamine ( can't open even from launcher icon)

So each time i accidentally close dopamine to tray, i have to terminate from system monitor to open again

**Comment by digimezzo** [comment] 2024-09-30 13:40
@akano12, @413Michele, I created a build containing a fix for this problem. Could you try it out and report back? Thanks!
The build is here: https://github.com/digimezzo/dopamine/actions/runs/11107123120

**Comment by 413Michele** [comment] 2024-09-30 14:12
> @akano12, @413Michele, I created a build containing a fix for this problem. Could you try it out and report back? Thanks! The build is here: https://github.com/digimezzo/dopamine/actions/runs/11107123120

I can confirm it works on Windows👍The icon shows and the contxt menu opens (btw I thought double clicking the icon opened the main window but it doesn't do that, was I mistaken?)

I can't test on Linux right now but I will report later

**Comment by digimezzo** [comment] 2024-09-30 14:19
@413Michele Thanks for testing it out! Double clicking on the icon never did anything. It looks like an easy feature but it isn't :) I wasn't able to get it to work yet.

**Comment by 413Michele** [comment] 2024-09-30 21:54
Tested and verified no problems on KDE Neon either, thanks!

**Comment by digimezzo** [comment] 2024-10-01 04:14
Thank you all for testing it out. I'll release the fix in preview 35.

**Closed** 2024-10-01 20:00 UTC
Labels: bug
